Areas/Admin/Components/PagingViewComponent.cs
using Coza_Ecommerce_Shop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Coza_Ecommerce_Shop.Areas.Admin.Components
{
    public class PagingViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(PagingViewModel model)
        {
            return View(model); 
        }
    }
}

Controllers/NewsController.cs
using Coza_Ecommerce_Shop.Repositories.Interfaces;
using Coza_Ecommerce_Shop.ViewModels.Product;
using Coza_Ecommerce_Shop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Printing;
using X.PagedList.Extensions;

namespace Coza_Ecommerce_Shop.Controllers
{
    [Route("news")]
    public class NewsController : Controller
    {
        private readonly INewRepository _newRepository;

        public NewsController(INewRepository newRepository)
        {
            _newRepository = newRepository;
        }

        [HttpGet("")]
        [HttpGet("[action]")]
        public async Task<IActionResult> Index (int? page = 1)
        {
            int pageSize = 9;
            int pageNumber = page ?? 1;

            var query = await _newRepository.GetAllAsync();
            var totalData = query.Count();

            var totalPages = (int)Math.Ceiling((double)totalData / pageSize);

            pageNumber = pageNumber > totalPages ? totalPages : pageNumber;

            var pagedList = query.OrderByDescending(x => x.CreateDate).ToPagedList(pageNumber, pageSize);


            var NewsViewModel = new NewsViewModel
            {
                News = pagedList,
                PagingInfo = new PagingViewModel
                {
                    CurrentPage = pageNumber,
                    TotalCount = pagedList.Count,
                    PageSize = pageSize,
                    TotalPages = totalPages,
                }
            };
            return View(NewsViewModel);
        }


        [HttpGet("detail/{slug}")]
        public async Task<IActionResult> Details(string slug)
        {
            if (string.IsNullOrWhiteSpace(slug))
            {
                return NotFound("Không tìm thấy tin tức");
            }

            var model = await _newRepository.GetBySlugAsync(slug);
            return View(model);

        }
    }
}

Views/Shared/Components/LatestNews/Default.cshtml
@using System.Globalization
@model IEnumerable<Coza_Ecommerce_Shop.Models.Entities.New>

<div class="card">
    <div class="card-header">
        <h4 class="text-center">Tin tức mới nhất</h4>
    </div>
    <div class="card-body">
        <div class="list-group">
            @foreach(var item in Model)
            {
                <a asp-controller="News" asp-action="Details" asp-route-slug="@item.Slug" class="list-group-item list-group-item-action px-0 bor-none d-flex align-items-center">
                    <div class="news-img-container">
                        <img src="@item.Image" alt="news-img" class="news-img">
                    </div>
                    <div class="m-l-10 text-truncate">
                        <p class="mb-1 stext-110 cl2 hov-cl1 trans-04 news-title">@item.Title</p>
                        <small class="text-muted">
                            @item.CreateDate.ToString("dd MMMM, yyyy", new CultureInfo("vi-VN"))
                        </small>
                    </div>
                </a>
            }
            
            
        </div>
    </div>
</div>