ViewModels/Product/ParamsFilter.cs
namespace Coza_Ecommerce_Shop.ViewModels.Product
{
    public class ParamsFilter
    {
        public int? page { set; get; }
        public string? slug { set; get; }
        public string? search { set; get; }
        public string? sort { set; get; }
        public int? minPrice { set; get; }
        public int? maxPrice { set; get; }
    }
}

Areas/Admin/Components/PagingViewComponent.cs
using Coza_Ecommerce_Shop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Coza_Ecommerce_Shop.Areas.Admin.Components
{
    public class PagingViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(PagingViewModel model)
        {
            return View(model); 
        }
    }
}

Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Coza_Ecommerce_Shop.Data;
using Coza_Ecommerce_Shop.Models.Entities;
using AspNetCoreHero.ToastNotification.Abstractions;
using Coza_Ecommerce_Shop.Models.Common;
using Coza_Ecommerce_Shop.ViewModels;
using System.Collections;
using Coza_Ecommerce_Shop.Repositories.Interfaces;
using Coza_Ecommerce_Shop.ViewModels.Product;
using AutoMapper;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Globalization;
using System.Text;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using X.PagedList.Extensions;
using Coza_Ecommerce_Shop.Models.Helper;
using Coza_Ecommerce_Shop.Repositories.Implementations;
using NuGet.Packaging;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Server.IISIntegration;
using Microsoft.AspNetCore.Authorization;

namespace Coza_Ecommerce_Shop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(AuthenticationSchemes = "AdminScheme")]
    public class ProductsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IProductRepository _productRepository;
        private readonly IProductCategoryRepository _productCategoryRepository;

        private readonly IProductVariantRepository _productVariantRepository;

        private readonly ILogger<ProductsController> _logger;
        public INotyfService _notifyService { get; }

        public ProductsController
        (

            ILogger<ProductsController> logger,
            IMapper mapper, IProductRepository productRepository,
            IProductCategoryRepository productCategoryRepository,

            IProductVariantRepository productVariantRepository,
            INotyfService notifyService
        )
        {
            _logger = logger;
            _mapper = mapper;
            _productRepository = productRepository;
            _productCategoryRepository = productCategoryRepository;
            _productVariantRepository = productVariantRepository;
            _notifyService = notifyService;
        }


        private string GenerateProductSKU()
        {
            string guidPart = Guid.NewGuid().ToString("N").Substring(0, 8).ToUpper();
            return $"PRD-{guidPart}";
        }

        private string GenerateSKUVariant(string productCode, int variantNumber)
        {
            return $"{productCode}-{variantNumber:D2}";
        }

        // GET: Admin/Products
        [HttpGet]
        public async Task<IActionResult> Index(string search, int? page = 1)
        {
            var listproducts = await _productRepository.GetAllAsync();
            if (!string.IsNullOrEmpty(search))
            {
                listproducts = listproducts.Where(x => x.Title.ToLower().Contains(search.ToLower()) || (x.ProductCode != null && x.ProductCode.ToLower().Contains(search.ToLower())));
            }


            int pageSize = 5;
            int pageNumber = page ?? 1;
            var totalData = listproducts.Count();

            var totalPages = totalData > 0 ? (int)Math.Ceiling((double)totalData / pageSize) : 1;


            pageNumber = pageNumber > totalPages ? totalPages : pageNumber;

            var pagedList = listproducts.OrderByDescending(x => x.Id).ToPagedList(pageNumber, pageSize);


            var ProductsPagingViewModel = new ProductsPagingViewModel
            {
                Products = pagedList,
                PagingInfo = new PagingViewModel
                {
                    CurrentPage = pageNumber,
                    TotalCount = pagedList.Count,
                    PageSize = pageSize,
                    TotalPages = totalPages,
                    SearchTerm = search,
                }
            };

            return View(ProductsPagingViewModel);
        }

        // GET: Admin/Products/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productdetail = await _productRepository.GetDetailProductByIdAsync(id);

            if (productdetail == null)
            {
                return NotFound();
            }
            return View(productdetail);
        }

        private bool ValidateCreateProductViewModel(ProductViewModel productViewModel)
        {

            if (productViewModel.Variants.Any(x => x.BasePrice == null || x.Quantity == null))
            {
                ModelState.AddModelError("", "Chưa nhập đủ thông tin cho các biến thể của sản phẩm.");
                return false;
            }

            if (productViewModel.Files == null || productViewModel.Files.Count == 0)
            {
                ModelState.AddModelError("Files", "Sản phẩm có ít nhất 1 ảnh.");
                return false;
            }

            if (productViewModel.Variants == null || !productViewModel.Variants.Any())
            {
                ModelState.AddModelError("", "Sản phẩm có ít nhất 1 biến thể.");
                return false;
            }

            var duplicateVariants = productViewModel.Variants
                .GroupBy(v => new { v.Color, v.Size }) // Nhóm theo Color và Size
                .Where(g => g.Count() > 1)
                 .SelectMany(g => g.Skip(1))
                .ToList();

            if (duplicateVariants.Any())
            {
                string strerr = "";
                foreach (var variant in duplicateVariants)
                {
                    strerr += $"Biến thể bị trùng: Màu {variant.Color}, Size {variant.Size}";
                }

                ModelState.AddModelError("", strerr);
                return false;
            }

            if (!ProcessProductImages(productViewModel))
            {
                return false;
            }

            return true;
        }

        private bool ValidateEditProductViewModel(ProductViewModel productViewModel)
        {
            if (productViewModel.Variants.Any(x => x.Color == null || x.Size == null || x.BasePrice == null || x.Quantity == null))
            {
                ModelState.AddModelError("ErrorVariant", "Chưa nhập đủ thông tin cho các biến thể của sản phẩm.");
                return false;
            }

            var duplicateVariants = productViewModel.Variants
               .GroupBy(v => new { v.Color, v.Size })
               .Where(g => g.Count() > 1)
                .SelectMany(g => g.Skip(1))
               .ToList();

            if (duplicateVariants.Any())
            {
                string strerr = "";
                foreach (var variant in duplicateVariants)
                {
                    strerr += $"Biến thể bị trùng: Màu {variant.Color}, Size {variant.Size}";
                }

                ModelState.AddModelError("ErrorVariant", strerr);
                return false;
            }

            return true;
        }

        private bool ProcessProductImages(ProductViewModel productViewModel)
        {
            foreach (var file in productViewModel.Files)
            {
                if (file.Length > 8 * 1024 * 1024) // 8MB
                {
                    ModelState.AddModelError("Files", "File không được lớn hơn 8MB.");
                    return false;
                }

                var allowedExtensions = new[] { ".jpg", ".png", ".jpeg", ".gif" };
                if (!allowedExtensions.Contains(Path.GetExtension(file.FileName).ToLower()))
                {
                    ModelState.AddModelError("Files", "Chỉ hỗ trợ định dạng JPG, PNG, JPEG, GIF.");
                    return false;
                }
            }
            return true;
        }

        private void ProcessVariants(ProductViewModel productViewModel, Product product)
        {
            int variantNumber = 0;
            var existingVariants = product.Variants.ToList();
            var listsku = existingVariants.Select(x => x.SKU).ToList();
            foreach (var item in productViewModel.Variants)
            {

                var existingVariant = existingVariants.FirstOrDefault(v => v.Id == item.Id);
                if (existingVariant == null)
                {
                    item.Id ??= Guid.NewGuid();
                    var newsku = GenerateSKUVariant(productViewModel.ProductCode, ++variantNumber);
                    while (listsku.Contains(newsku))
                    {
                        newsku = GenerateSKUVariant(productViewModel.ProductCode, ++variantNumber);
                    }
                    item.SKU = newsku;
                    item.SKU = GenerateSKUVariant(productViewModel.ProductCode, ++variantNumber);
                    item.ProductId = product.Id;
                    item.BasePrice ??= 0;
                    item.PriceSale ??= 0;
                    item.Quantity ??= 0;
                    item.IsActive = true;

                    product.Variants.Add(new ProductVariant
                    {
                        Id = item.Id.Value,
                        ProductId = product.Id,
                        SKU = item.SKU,
                        Color = item.Color,
                        Size = item.Size,
                        BasePrice = item.BasePrice.Value,
                        PriceSale = item.PriceSale.Value,
                        Quantity = item.Quantity.Value,
                        IsActive = item.IsActive,
                        IsDefault = item.IsDefault
                    });
                }
                else
                {
                    // Cập nhật biến thể đã tồn tại
                    existingVariant.SKU = existingVariant.SKU;
                    existingVariant.Color = item.Color;

Controllers/ProductController.cs
using AutoMapper;
using Coza_Ecommerce_Shop.Repositories.Interfaces;
using Coza_Ecommerce_Shop.ViewModels.Product;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json.Serialization;
using System.Text.Json;
using Coza_Ecommerce_Shop.Services;
using Coza_Ecommerce_Shop.ViewModels;
using Coza_Ecommerce_Shop.Models.Entities;
using System.Security.Claims;

namespace Coza_Ecommerce_Shop.Controllers
{
    [Route("product")]
    public class ProductController : Controller
    {

        private readonly IProductRepository _productRepository;
        private readonly IProductCategoryRepository _productCategoryRepository;
        private readonly IProductCategoryService _productCategoryService;
        private readonly IProductService _productService;
        private readonly UserService _userService;
        private readonly IMapper _mapper;

        public ProductController(IProductRepository productRepository, IProductCategoryRepository productCategoryRepository, IProductCategoryService productCategoryService, IProductService productService, UserService userService, IMapper mapper)
        {
            _productRepository = productRepository;
            _productCategoryRepository = productCategoryRepository;
            _productCategoryService = productCategoryService;
            _productService = productService;
            _userService = userService;
            _mapper = mapper;
        }

        [HttpGet("product-detail/{slug}")]
        public async Task<IActionResult> ProductDetail(string slug)
        {
            var product = await _productRepository.GetDetailProductBySlugAsync(slug);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);

        }

        [HttpGet("list-product")]
        public async Task<IActionResult> ListProduct([FromQuery] ParamsFilter filter)
        {
            var breadCrumbShow = "Sản phẩm";
            var productsListViewModel = new ProductsListViewModel();

            if (!string.IsNullOrEmpty(filter.slug))
            {
                var productCategory = await _productCategoryRepository.GetBySlugAsNoTrackingAsync(filter.slug);
                if (productCategory != null)
                {
                    breadCrumbShow = productCategory.Title;
                }
            }
            productsListViewModel.breadCrumbShow = breadCrumbShow;
            productsListViewModel.paramsFilter = filter;

            return View(productsListViewModel);
        }

        [HttpGet("load-more-product")]
        public async Task<IActionResult> LoadMore(int? page = 1)
        {
            ++page;
            int pageSize = 4;

            var data = await _productService.GetProductByPage(page.Value, pageSize);
            return Json(new
            {
                products = data,
                nextPage = page
            }, new JsonSerializerOptions
            {
                ReferenceHandler = ReferenceHandler.IgnoreCycles,
                WriteIndented = true
            });

        }


        [HttpGet("GetVariant")]
        public async Task<IActionResult> GetVariant(string sku, string color, string size)
        {
            var product = await _productRepository.GetDetailProductBySKUAsync(sku);
            if (product == null)
            {
                return NotFound();
            }

            var selectedVariant = product.Variants
                                .FirstOrDefault(v => v.Color == color && v.Size == size);
            if (selectedVariant == null)
            {
                return NotFound("Variant không tồn tại");
            }

            var ObjVariant = _mapper.Map<ProductVariantsViewModel>(selectedVariant);


            return Json(new
            {
                variant = ObjVariant
            });

        }

        [HttpGet("get-variants")]
        public async Task<IActionResult> GetVariantsForProduct(string sku)
        {
            var product = await _productRepository.GetDetailProductBySKUAsync(sku);
            if (product == null)
            {
                return NotFound();
            }

            var selectedVariant = product.Variants;
            if (selectedVariant == null)
            {
                return NotFound("Variant không tồn tại");
            }

            var variants = product.Variants.Select(v => new
            {
                size = v.Size,
                color = v.Color,
                stock = v.IsActive ? v.Quantity : 0
            }).ToList();

            return Json(new { variants });
        }

        [HttpPost("load-wishlist")]
        public async Task<IActionResult> LoadWishlist()
        {
            var userPrincipal = await _userService.GetUserByUserTypeAsync("Customer");
            if (userPrincipal == null)
            {
                return BadRequest(new { isLogin = false, message = "Chưa đăng nhập" });
            }
            var userid = userPrincipal.FindFirst("Id").Value;
            var rs = await _productRepository.GetWishlistByUserid(userid.ToString());
            return Ok(new { issuccess = true, data = rs });
        }

        [HttpPost("add-to-wishlist")]
        public async Task<IActionResult> AddToWishlist([FromBody] WishlistRequestViewModel model)
        {
            var userPrincipal = await _userService.GetUserByUserTypeAsync("Customer");
            if (userPrincipal == null)
            {
                return BadRequest(new { isLogin = false, message = "Chưa đăng nhập" });
            }
            if (model.productid == Guid.Empty)
            {
                return BadRequest(new { isLogin = true, message = "Thêm thất bại" });
            }

            var userid = userPrincipal.FindFirst("Id").Value;
            Wishlist wishlist = new Wishlist
            {
                ProductId = model.productid,
                UserId = userid.ToString()
            };
            var (IsSuccess, ErrorMessage) = await _productRepository.AddToWishlist(wishlist);
            return Ok(new { isAdded = IsSuccess, message = IsSuccess ? "Đã thêm vào danh sách yêu thích" : ErrorMessage });

        }

        [HttpGet("my-wishlist")]
        public async Task<IActionResult> MyWishlist()
        {
            var userPrincipal = await _userService.GetUserByUserTypeAsync("Customer");
            if (userPrincipal == null)
            {
                return RedirectToAction("login", "account");
            }
            var userid = userPrincipal.FindFirst("Id").Value;
            var listProductWishtlist = await _productRepository.GetProductWishlistByUserid(userid.ToString());
            
            return View(listProductWishtlist);
        }

    }
}

ViewComponents/UserPagingViewComponent.cs
using Coza_Ecommerce_Shop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Coza_Ecommerce_Shop.ViewComponents
{
    public class UserPagingViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagingViewModel model)
        {
            return Task.FromResult((IViewComponentResult)View(model));
        }
    }
}

Views/Shared/Components/Product/Default.cshtml
@using System.Globalization
@model Coza_Ecommerce_Shop.ViewModels.Home.ProductOverViewVM

@functions {
    string BuildPageUrl(int? page = null,string? slug = null, string? search = null, int? minPrice = null, int? maxPrice = null, string? sort = null)
    {
        var queryParams = new Dictionary<string, object?>
        {
            { "page", page ?? Model.page },
            { "slug",  slug ?? Model.pagingViewModel.Slug },
            { "search", search ?? Model.pagingViewModel.SearchTerm },
            { "minPrice", minPrice ?? Model.pagingViewModel.PriceMin },
            { "maxPrice", maxPrice ?? Model.pagingViewModel.PriceMax },
            { "sort", sort ?? Model.pagingViewModel.SortOrder }
        };

        return Url.Action(null, queryParams);
    }
}

@{
    var Categories = Model.categories;
    var Products = Model.products;
    var controllerName = ViewContext.RouteData.Values["controller"]?.ToString() ?? "Home";
    
    var sortOrder = Model.pagingViewModel?.SortOrder?.ToLower();
}

<div class="flex-w flex-sb-m p-b-52">
    <div class="flex-w flex-l-m m-tb-10">
        <button class="all-product-btn stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1">
            All Products
        </button>

        @foreach (var item in Categories)
        {
            <a href="@BuildPageUrl(slug: item.Slug)" class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5">
                @item.Title
            </a>
        }
       
    </div>

    <!-- filter box-->
    @if (controllerName.ToLower() == "product")
    {

        <div class="flex-w flex-c-m m-tb-10">
            <div class="flex-c-m stext-106 cl6 size-104 bor4 pointer hov-btn3 trans-04 m-r-8 m-tb-4 js-show-filter">
                <i class="icon-filter cl2 m-r-6 fs-15 trans-04 zmdi zmdi-filter-list"></i>
                <i class="icon-close-filter cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none"></i>
                Filter
            </div>

            <div class="flex-c-m stext-106 cl6 size-105 bor4 pointer hov-btn3 trans-04 m-tb-4 js-show-search">
                <i class="icon-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-search"></i>
                <i class="icon-close-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none"></i>
                Search
            </div>
        </div>

        <!-- Search product -->
        
        <div class="dis-none panel-search w-full p-t-10 p-b-15">
            <form asp-controller="Product" asp-action="ListProduct" method="get">
                <div class="bor8 dis-flex p-l-15">
                    <button type="submit" class="size-113 flex-c-m fs-16 cl2 hov-cl1 trans-04">
                        <i class="zmdi zmdi-search"></i>
                    </button>

                    <input type="hidden" name="page" value="@Model.page">
                    <input type="hidden" name="slug" value="@Model.pagingViewModel?.Slug">
                    <input class="mtext-107 cl2 size-114 plh2 p-r-15" value="@Model.pagingViewModel?.SearchTerm" type="text" name="search" placeholder="Search">
                    <input type="hidden" name="minPrice" value="@Model.pagingViewModel?.PriceMin">
                    <input type="hidden" name="maxPrice" value="@Model.pagingViewModel?.PriceMax">
                    <input type="hidden" name="sort" value="@Model.pagingViewModel?.SortOrder">

                </div>
            </form>
        </div>

        <!-- Filter -->
        <div class="dis-none panel-filter w-full p-t-10">
            <div class="wrap-filter flex-w bg6 w-full p-lr-40 p-t-27 p-lr-15-sm">
                <div class="filter-col1 p-r-15 p-b-27">
                    <div class="mtext-102 cl2 p-b-15">
                        Sort By
                    </div>

                    <ul>

                        <li class="p-b-6">
                            <a href="@BuildPageUrl(sort: "default")" class="filter-link stext-106 trans-04 @(sortOrder == "default" || string.IsNullOrEmpty(sortOrder) ? "filter-link-active" : "")">
                                Mặc định
                            </a>
                        </li>
                        <li class="p-b-6">
                            <a href="@BuildPageUrl(sort: "newest")" class="filter-link stext-106 trans-04 @(sortOrder == "newest" ? "filter-link-active" : "")">
                                Mới nhất
                            </a>
                        </li>

                        <li class="p-b-6">
                            <a href="@BuildPageUrl(sort: "price-desc")" class="filter-link stext-106 trans-04 @(sortOrder == "price-desc" ? "filter-link-active" : "")">
                                Giá giảm dần
                            </a>
                        </li>

                        <li class="p-b-6">
                            <a href="@BuildPageUrl(sort: "price-asc")" class="filter-link stext-106 trans-04 @(sortOrder == "price-asc" ? "filter-link-active" : "")">
                                Giá tăng dần
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="filter-col2 p-r-15 p-b-27">
                    <div class="mtext-102 cl2 p-b-15">
                        Price
                    </div>
                    
                    <form asp-controller="Product" asp-action="ListProduct" method="get">

                        <input type="hidden" name="page" value="@Model.page">
                        <input type="hidden" name="slug" value="@Model.pagingViewModel?.Slug">
                        <input type="hidden" name="search" value="@Model.pagingViewModel?.SearchTerm">


                        <div class="range-slider">
                            <input type="range" id="min-price" name="minPrice" min="0" max="2000000" step="10000" value="@(Model.pagingViewModel.PriceMin ?? 0)">
                            <input type="range" id="max-price" name="maxPrice" min="0" max="2000000" step="10000" value="@(Model.pagingViewModel.PriceMax ?? 2000000)">
                            <div class="slider-track"></div>
                        </div>

                        <input type="hidden" name="sort" value="@Model.pagingViewModel?.SortOrder">


                        <div class="price-values">
                            <span id="min-value">0đ</span>
                            <span id="max-value">2,000,000đ</span>
                        </div>

                      
                        <button type="submit" class="btn btn-filter mt-3">
                            <i class="zmdi zmdi-filter-list"></i> Lọc
                        </button>
                    </form>

                    
                </div>

                <div class="filter-col3 p-b-27">
                    <div class="mtext-102 cl2 p-b-15">
                        Tags
                    </div>

                    <div class="flex-w p-t-4 m-r--5">
                        <a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
                            Fashion
                        </a>

                        <a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
                            Lifestyle
                        </a>

                        <a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
                            Denim
                        </a>

                        <a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
                            Streetstyle
                        </a>

                        <a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
                            Crafts
                        </a>
                    </div>
                </div>

            </div>
        </div>
    }
</div>




<div class="row isotope-grid product-container">
    @foreach (var product in Products)
    {
        var productDefault = product.Variants.FirstOrDefault(x => x.IsDefault);
        if (productDefault == null)
        {
            productDefault = product.Variants.First();
        }
        var basePrice = (productDefault.BasePrice != null ? productDefault.BasePrice?.ToString("#,0", new CultureInfo("vi-VN")) : "0") + "đ";
        <div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item">
            <!-- Block2 -->
            <div class="block2">
                <div class="block2-pic hov-img0">
                    <img src="@product.Image" alt="IMG-PRODUCT">
                    <a href="#" data-id="@product.Id" class="quick-order-btn block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1">
                        Quick View
                    </a>
                </div>

                <div class="block2-txt flex-w flex-t p-t-14 product-detail">
                    <div class="block2-txt-child1 flex-col-l ">
                        <a asp-controller="Product" asp-action="ProductDetail" asp-route-slug="@product.Slug" class="stext-104 cl4 hov-cl1 trans-04 js-name-detail p-b-6">
                            @product.Title
                        </a>

                        <span class="stext-105 cl3">
                            @basePrice
                        </span>
                    </div>

                    <div class="block2-txt-child2 flex-r p-t-3">
                        <a href="#" data-id="@product.Id" class="btn-addwish dis-block pos-relative">
                            <img class="icon-heart1 dis-block trans-04" src="~/assets/images/icons/icon-heart-01.png" alt="ICON">
                            <img class="icon-heart2 dis-block trans-04 ab-t-l" src="~/assets/images/icons/icon-heart-02.png" alt="ICON">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>



@if (controllerName.ToLower() == "product")
{
    @await Component.InvokeAsync("UserPaging", new { model = Model.pagingViewModel })
}